### ISSUE TITLE
Munge data in aggregator

### ISSUE THREAD

**Issue by jgrund** [intel-hpdd/device-scanner#146]
Instead of munging device trees together in:

https://github.com/intel-hpdd/intel-manager-for-lustre/blob/79c9961af61b2991c38c7626f5d665c12dd51359/chroma-manager/chroma_core/plugins/block_devices.py#L1-L559

Perform the munging in the device-aggregator.

By doing this we can make sure the munging is typesafe and syncs with any upstream changes in device-scanner.

**Comment by tanabarr** [comment]
presumably this will consume a large mount of the changes within https://github.com/intel-hpdd/intel-manager-for-lustre/pull/456
