### ISSUE TITLE
install fails without zfs installed

### ISSUE THREAD

**Issue by tanabarr** [intel-hpdd/device-scanner#158]
when installing the `iml-device-scanner` rpm, still executing the triggerin scriptlet on scanner install even if zfs is not installed:
```
Apr 24 09:00:09 lotus-32vm5 systemd[1]: device-scanner.service: main process exited, code=killed, status=11/SEGV
Apr 24 09:00:09 lotus-32vm5 systemd[1]: Unit device-scanner.service entered failed state.
Apr 24 09:00:09 lotus-32vm5 systemd[1]: device-scanner.service failed.
Apr 24 09:00:09 lotus-32vm5 systemd[1]: device-scanner.service holdoff time over, scheduling restart.
Apr 24 09:00:09 lotus-32vm5 systemd[1]: Started IML Device Scanner Daemon.
```
```
Running transaction
  Installing : iml-device-scanner-2.1.0-2.el7.centos.x86_64                                                                1/1
Created symlink from /etc/systemd/system/sockets.target.wants/device-scanner.socket to /usr/lib/systemd/system/device-scanner.socket.
modprobe: FATAL: Module zfs not found.
  Verifying  : iml-device-scanner-2.1.0-2.el7.centos.x86_64                                                                1/1

Installed:
  iml-device-scanner.x86_64 0:2.1.0-2.el7.centos

Complete!
```

**Comment by jgrund** [comment]
It looks like zfs is installed on that node though?

**Comment by tanabarr** [comment]
not a bug, broken installations not supported

**Comment by brianjmurrell** [comment]
> Apr 24 09:00:09 lotus-32vm5 systemd[1]: device-scanner.service: main process exited, code=killed, status=11/SEGV

... is a really bad way to handle even _invalid_/_broken_ installations.  An executable should **never** segfault.

Even if the working environment is not sane, the insanity should be detected and an error message emitted and the executable should exit with a failure code.

**Comment by jgrund** [comment]
Can we open a new issue here?

Even though I agree with the sentiment, the original issue does not reflect the last comment.

**Comment by jgrund** [comment]
Opened https://github.com/intel-hpdd/rust-libzfs/issues/59 to address.

The latest spec updates gate any zfs commands on the zfs kernel module loading successfully.
