### ISSUE TITLE
zpool identifier consistency

### ISSUE THREAD

**Issue by tanabarr** [intel-hpdd/device-scanner#72]
In the ZED output from the device scanner, zpool guids don't contain leading zeros whereas the zfs poolGuid does. 

```
"zed":{"zpools":{"0x4e1f2b3ba6f5ce9":{"name":"testPool4","guid":"0x4e1f2b3ba6f5ce9",
...
"zfs":[{"poolGuid":"0x04e1f2b3ba6f5ce9","name":"testPool4/ds1"}],
```

**Comment by jgrund** [comment]
It looks like the rust version (libzfs) does not include a leading 0, but the zed version does.

**Comment by jgrund** [comment]
So, what's happening is ZED is left padding the hex number with 0's to have 16 chars after the `0x`.

I can do the same in rust-libzfs. Closing this and moving issue there.
