### ISSUE TITLE
Stop services when removed in IML UI

### ISSUE THREAD

**Issue by tanabarr** [intel-hpdd/device-scanner#94]
When storage server is removed in the UI, the `scanner-proxy` and (possibly) `device-scanner` services should be stopped so that the `device-aggregator` does not report their presence to the resource manager.

A possible change could be that the agent and all related services and packages are removed from the host when it is removed from the UI although that is not currently the case.

**Comment by jgrund** [comment]
> A possible change could be that the agent and all related services and packages are removed from the host when it is removed from the UI although that is not currently the case.

I was wondering this. This seems like the right fix, is there a reason we don't do this today?

**Comment by tanabarr** [comment]
I don't know the reason we don't, I imagine just for the speed of reinstalling, but I don't think it's worth that really. maybe also diagnostics/recovery reasons?

**Comment by jgrund** [comment]
Before I forget, if we decide to remove the packages it looks like ```yum autoremove``` may work.

**Comment by jgrund** [comment]
Going to fix this in the https://github.com/intel-hpdd/intel-manager-for-lustre repo.

**Comment by jgrund** [comment]
FWIW, one of the current advantages of keeping the packages after remove is that we kind of coopt that for faster install times for SSI and EFS testing.

In the long term I think autoremove is most likely the cleaner way to do this.
